spring:
  application:
    name: api
  profiles:
    active: local
    group:
      local: local-config, local-db
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: 8088


