spring:
  config:
    activate:
      on-profile: local-db
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306
      username: root
      password: 1234
      minimum-idle: 1
      maximum-pool-size: 10
  data:
    redis:
      host: localhost
      port: 6379
      connect-timeout: 3000
      timeout: 3000
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    default-schema: common

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 1000
        hibernate.transaction.jta.platform: org.hibernate.service.jta.JtaPlatform
